//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireNetWork.Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceAnswerOptions
    {
        public int Id { get; set; }
        public int AnswerId { get; set; }
        public int ChoiceId { get; set; }
        public int OptionId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual ChoiceQuestion ChoiceQuestion { get; set; }
        public virtual Option Option { get; set; }
    }
}
