//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireNetWork.Service.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestionnaireDBContext : DbContext
    {
        public QuestionnaireDBContext()
            : base("name=QuestionnaireDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<ChoiceAnswerOptions> ChoiceAnswerOptions { get; set; }
        public virtual DbSet<ChoiceQuestion> ChoiceQuestion { get; set; }
        public virtual DbSet<Completion> Completion { get; set; }
        public virtual DbSet<CompletionAnswerOptions> CompletionAnswerOptions { get; set; }
        public virtual DbSet<Option> Option { get; set; }
        public virtual DbSet<Questionnaire> Questionnaire { get; set; }
    }
}
