//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireNetWork.Web.ViewModels
{
    public partial class OptionViewModel
    {
        public int OptionId { get; set; }
        public int ChoiceId { get; set; }
        public string OptionContent { get; set; }
    }
}
